from lexer_TP1 import lexer

print(lexer("mientras 69 esMenorQue (contador + 45)"))
print(lexer("mientras = * + ( ) si sino entonces mostrar aceptar esMenorQue hacer op clp"))
print(lexer("si (43 = 21)"))
print(lexer("si (43=25) entonces mostrar variable"))
print(lexer("si$ 67 ent#onces"))
print(lexer("23asd"))
print(lexer("mientras 78 esMenorQue var hacer op clp"))
print(lexer("si (43=25) entonces mostrar variable"))
print(lexer("si (2 + 3) entonces / ()"))
print(lexer("mientras ( + )"))
print(lexer("34 = (2 + var"))
print(lexer("si entonces 23 / mientras #"))
print(lexer("mientras a < 97"))